### ISSUE TITLE
showing past codeforces contest as the present one

### ISSUE THREAD

**Issue by tushar-rishav** [architv/chcli#2]
Hey it's cool stuff! :sweat_smile:  But there is this bug. Umm  It seems like the json data which you are fetching has some wrong information. It shows codeforces past DIV2 (324) as the upcoming one ( which is rather 325 ).  
![bug](https://cloud.githubusercontent.com/assets/7397433/10369591/bcacb00c-6df8-11e5-829d-cb8df516d60a.png)
Similar issues with Codechef too.

**Comment by architv** [comment]
There was some error at the backend. Should be fixed now. Let me know if there is any other problem.

**Comment by tushar-rishav** [comment]
@architv Seems to be working fine now!  I guess you are sending a GET request. You don't have any  control on reliability of the json data being fetched. Right? May I please know what changes you have made to fix it? I couldn't find anything satisfactory in commits.

**Comment by architv** [comment]
@tushar-rishav I actually built the backend API, so I do have control over it. The crons weren't running earlier, which was causing the problem.

**Comment by tushar-rishav** [comment]
@architv  cool! I am terminating this thread.
